### ISSUE TITLE
new release tag, for OCEAN, by 2023-05-19 

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#119]
Blocked by

- [x] https://github.com/insightsengineering/rlistings/issues/96
- [x] https://github.com/insightsengineering/rlistings/issues/117

# TODOs

- [x]  Upstream formatters version bump to 0.5.0
- [x] #123
- [x]  Tag the update as a release candidate, v0.2.2-rc1
- [x]  Submit v0.2.2-rc1 for validation
- [x]  Get v0.2.2-rc1 validated, retag as v0.2.2
- [x]  Update downstream package dependencies to (>=0.2.2) in chevron
- [x]  Update downstream package dependencies to (>=0.2.2) in citril
